name: C++26 Strict CI

on:
  push:
      branches: [ "main" ]
  pull_request:
      branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-gcc-26:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/${{ github.repository_owner }}/mach-build-env:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies (Conan)
        run: |
            conan profile detect --force
            conan install . -pr:h ./conan/profiles/gcc-26 -pr:b default --build=missing

      - name: Build
        run: |
            conan build .  -pr:h ./conan/profiles/gcc-26 -pr:b default --build=missing
