name: Pipeline

on:
  push:
      branches: [ "main" ]
      paths-ignore:
        - '.devcontainer/**'
  pull_request:
      branches: [ "main" ]
      paths-ignore:
        - '.devcontainer/**'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  lint:
    runs-on: ubuntu-latest

    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}

    container:
      image: ghcr.io/${{ github.repository_owner }}/mach-build-env:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Mark repository safe for Git
        run: |
            git config --global --add safe.directory "$(pwd)"

      - name: Run Linter
        run: |
            bash scripts/lint

  clang-tidy:
    runs-on: ubuntu-latest

    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}

    container:
      image: ghcr.io/${{ github.repository_owner }}/mach-build-env:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies (Conan)
        run: |
            conan profile detect --force
            conan install . -pr:h ./conan/profiles/gcc-26 -pr:b default --build=missing

      - name: Build
        run: |
            conan build .  -pr:h ./conan/profiles/gcc-26 -pr:b default --build=missing

      - name: Run Clang-Tidy
        run: |
            bash scripts/clang-tidy

  build-gcc-26:
    runs-on: ubuntu-latest

    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}

    container:
      image: ghcr.io/${{ github.repository_owner }}/mach-build-env:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies (Conan)
        run: |
            conan profile detect --force
            conan install . -pr:h ./conan/profiles/gcc-26 -pr:b default --build=missing

      - name: Build
        run: |
            conan build .  -pr:h ./conan/profiles/gcc-26 -pr:b default --build=missing

  build-gcc-26-debug:
    runs-on: ubuntu-latest

    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}

    container:
      image: ghcr.io/${{ github.repository_owner }}/mach-build-env:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies (Conan)
        run: |
            conan profile detect --force
            conan install . -pr:h ./conan/profiles/gcc-26-debug -pr:b default --build=missing

      - name: Build
        run: |
            conan build .  -pr:h ./conan/profiles/gcc-26-debug -pr:b default --build=missing

  run-unit-tests-release:
    runs-on: ubuntu-latest
    needs: [build-gcc-26, build-gcc-26-debug]

    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}

    container:
      image: ghcr.io/${{ github.repository_owner }}/mach-build-env:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies (Conan)
        run: |
            conan profile detect --force
            conan install . -pr:h ./conan/profiles/gcc-26 -pr:b default --build=missing

      - name: Build (for tests)
        run: |
            conan build .  -pr:h ./conan/profiles/gcc-26 -pr:b default --build=missing

      - name: Run Unit Tests
        run: |
            cd build/Release
            ctest -V
